#! /bin/sh
# Runit startup script
# 
# Saves the container's environment variables and runs any scripts found in
# /etc/startup.d before starting the main runit process.
#
# Inspired by https://github.com/faisyl/alpine-runit (thanks)

# export the environment
export > /etc/envvars
chmod 700 /etc/envvars

# run startup hooks
for script in /etc/startup.d/*; do
    if [ -x "$script" ]; then
        echo >&2 "*** Running $script ..."
        $script
        retval=$?
        if [ $retval != 0 ]; then
            echo >&2 "*** Failed with: $?"
            exit $retval
        fi
    fi
done

# run runit!
echo >&2 "*** Starting runit"
# don't use exec because runit doesn't respond to SIGINT
/sbin/runsvdir -P /etc/service

