version: '2'
services:
  frontend:
    build: images/frontend-nginx/
    ports:
     - "80:80"
    links:
     - ttrss
     - seafile
    volumes:  # seahub's media needs to be served by nginx
      - seafile:/opt/seafile/
  mysql:
    build: images/mysql/
    volumes:
      - mysql:/var/lib/mysql/
  ttrss:
    build: images/ttrss-nginx/
    volumes:
      - ttrss:/var/www/
    links:
      - mysql
  seafile:
    build: images/seafile/
    volumes:
      - seafile:/opt/seafile/
      - seafile_data:/var/seafile/
    links:
      - mysql

volumes:
  ttrss:
    driver: local-persist
    driver_opts: { mountpoint: /var/nas-data/ttrss }
  mysql:
    driver: local-persist
    driver_opts: { mountpoint: /var/nas-data/mysql }
  seafile:
    driver: local-persist
    driver_opts: { mountpoint: /var/nas-data/seafile }
  seafile_data:
    driver: local-persist
    driver_opts: { mountpoint: /var/nas-data/seafile_data }

