# Example Compose file using Docker Local Persist volumes.
version: '3'
services:
  frontend:
    image: nicloud/frontend-nginx:latest
    ports:
     - "80:80"
     - "443:443"
    links:
     - ttrss
     - seafile
    environment:
     - SSL_ENABLED=false
     - "DEFAULT_SNIPPETS=seafile ttrss"
    volumes:
     - nginx-config:/etc/nginx.overrides/
     - nginx-letsencrypt:/etc/letsencrypt/
     - seafile:/home/seafile/  # seahub's media needs to be served by nginx
  mysql:
    image: nicloud/mysql:latest
    volumes:
      - mysql:/var/lib/mysql/
  ttrss:
    image: nicloud/ttrss-nginx:latest
    volumes:
     - ttrss:/var/www/
    links:
     - mysql
  seafile:
    image: nicloud/seafile:latest
    volumes:
     - seafile:/home/seafile/
     - seafile-data:/var/lib/seafile/
    links:
     - mysql
    environment:
     - FASTCGI=true

volumes:
  nginx-config:
    driver_opts: {type: none, device: /var/nas-data/nginx-config, o: bind}
  nginx-letsencrypt:
    driver_opts: {type: none, device: /var/nas-data/nginx-letsencrypt, o: bind}
  ttrss:
    driver_opts: {type: none, device: /var/nas-data/ttrss, o: bind}
  mysql:
    driver_opts: {type: none, device: /var/nas-data/mysql, o: bind}
  seafile:
    driver_opts: {type: none, device: /var/nas-data/seafile, o: bind}
  seafile-data:
    driver_opts: {type: none, device: /var/nas-data/seafile-data, o: bind}

