version: '2'
services:
  frontend:
    build: images/frontend-nginx/
    ports:
     - "80:80"
     - "443:443"
    links:
     - ttrss
     - seafile
    environment:
     - SSL_ENABLED=false
     - "DEFAULT_SNIPPETS=seafile ttrss"
    volumes:
      - nginx_config:/etc/nginx.overrides/
      - letsencrypt:/etc/letsencrypt/
      - seafile:/opt/seafile/  # seahub's media needs to be served by nginx
  mysql:
    build: images/mysql/
    volumes:
      - mysql:/var/lib/mysql/
  ttrss:
    build: images/ttrss-nginx/
    volumes:
      - ttrss:/var/www/
    links:
      - mysql
  seafile:
    build: images/seafile/
    environment:
      - FASTCGI=true
    volumes:
      - seafile:/opt/seafile/
      - seafile_data:/var/seafile/
    links:
      - mysql

volumes:
  nginx_config:
    driver: local-persist
    driver_opts: { mountpoint: /var/nas-data/nginx-config }
  letsencrypt:
    driver: local-persist
    driver_opts: { mountpoint: /var/nas-data/letsencrypt }
  ttrss:
    driver: local-persist
    driver_opts: { mountpoint: /var/nas-data/ttrss }
  mysql:
    driver: local-persist
    driver_opts: { mountpoint: /var/nas-data/mysql }
  seafile:
    driver: local-persist
    driver_opts: { mountpoint: /var/nas-data/seafile }
  seafile_data:
    driver: local-persist
    driver_opts: { mountpoint: /var/nas-data/seafile_data }

